AWSTemplateFormatVersion: '2010-09-09'
Description: Parameter Stack

Parameters:
  PrivateHostedZoneName:
    Type: String
  EnableMasterHa:
    Type: String

Conditions:
  alwaysFalse: !Equals [ '1', '0' ]
  MasterHaEnabled: !Equals [ "true", !Ref EnableMasterHa ]

Resources:
  NoopResource:
    Type: AWS::IAM::User
    Condition: alwaysFalse

Outputs:
  SeedHosts:
    Value: !If [ MasterHaEnabled,
      !Sub '"es01.${PrivateHostedZoneName}","es02.${PrivateHostedZoneName}","es03.${PrivateHostedZoneName}"',
      !Sub '"es01.${PrivateHostedZoneName}"'
    ]
